version: '3.1'

# De services of 'containers' die gestart worden met docker-compose
services:

# De mongo database met een standaard gebruikersnaam en wachtwoord
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

# De mongo express UI die de mongo database in de andere container managed. Is bereikbaar via de browser op: localhost:8081
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example