FROM mcr.microsoft.com/dotnet/aspnet:5.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
WORKDIR /src
COPY ["Food.Service/FoodAPI/FoodAPI.csproj", "Food.Service/FoodAPI/"]
RUN dotnet restore "Food.Service/FoodAPI/FoodAPI.csproj"
COPY . .
WORKDIR "/src/Food.Service/FoodAPI"
RUN dotnet build "FoodAPI.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "FoodAPI.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "FoodAPI.dll"]

# Generated in VSCODE