name: Just-testing

on:
  workflow_dispatch:

env:
  SOLUTION_PATH: ./Food.Service/FoodAPI.sln
    
jobs:
  testing:
    name: testing solution
    
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with: 
          dotnet-version: 5.0.x
          
      - name: Restore Dependencies
        run: dotnet restore ${{ env.SOLUTION_PATH }}
          
      - name: Build Solution
        run: dotnet build --no-restore ${{ env.SOLUTION_PATH }}

      - name: Run tests
        run: dotnet test --no-build --verbosity normal ${{ env.SOLUTION_PATH }}
