name: CI-CD-FoodAPI

# Event on which the workflow triggers
on:
  workflow_dispatch:

# Variabelen die toegankelijk zijn voor alle jobs
env:
  SOLUTION_PATH: ./Food.Service/FoodAPI.sln
    
jobs:
  #2. Unit & Integration Testing
  unit-integration-testing:
    runs-on: ubuntu-latest

    # -Stappen voor Unit-Testing
    steps:
      - name: Checkout Repository
      - uses: actions/checkout@v2

      # -Zet environment op voor een recente versie van .NET 5
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x

      - name: Restore Dependencies
        run: dotnet restore ${{ SOLUTION_PATH }}

      - name: Build Solution
        run: dotnet build --no-restore ${{ SOLUTION_PATH }}

      # -Runs both unit and integration tests as they fall under one solution
      - name: Run tests
        run: dotnet test --no-build --verbosity normal ${{ SOLUTION_PATH }}
